httpd:
  port: 5099
  host: localhost
  request-logging: false
grpc:
  port: 2525
  host: localhost
database:
  file-based:
    directory: ./data  
logging:
  colored: true
  level: trace
  output: stdout
  report-caller: true
client-logging:
  colored: true
  level: debug
  output: stdout
  report-caller: true
